[package]
name = "tiling-mino-solver"
version = "0.2.6"
edition = "2024"

[dependencies]
nu-ansi-term = "0.50.3"
rayon = "1.10.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
tracing = "0.1.44"
tracing-subscriber = "0.3.20"
