[package]
name = "tiling-mino-solver"
version = "0.2.4"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
rayon = "1.10.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
